title: Jiayue Yang 
description: Freshman @ School of Cyber Science and Technology, USTC
email: jiayueyang@mail.ustc.edu.cn
theme: minima
social:
  github: jryyangjy
  email: jiayueyang@mail.ustc.edu.cn
theme: minima
plugins:
  - jekyll-sass-converter # 启用SASS编译
